  
#log config
logging: 
  config: classpath:log4j2.xml
  level: 
    root: DEBUG
    org: 
      springframework: 
        web: ERROR
        beans: ERROR
        core: ERROR
    springfox: ERROR

#数据库配置
spring: 
  profiles: 
    active: prod  
  servlet:
    multipart:
      maxFileSize: 500Mb
      maxRequestSize: 5000Mb
  resources: 
    static-locations: classpath:/static/
  mail:
    host: smtp.gmail.com
    username: up.knowledge.school@gmail.com        #lihuang.goo@gmail.com   #
    password: Knowledge2018         #zhenjiang
    protocol: smtp
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465
    properties.mail.display.sendmail: up.knowledge.school@gmail.com
    properties.mail.display.sendname: up.knowledge.school@gmail.com
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    from: up.knowledge.school@gmail.com
    default-encoding: utf-8
  
  
#mybatis配置
mybatis-plus:
  mapper-locations: classpath*:mappers/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.knowledge.**.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: false
    #字段自动填充
    meta-object-handler: com.knowledge.admin.base.config.mybatis.MyMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
